{"name": "test_loginTestsOne", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test_TestOne' object has no attribute 'accountNumber1'", "trace": "self = <Tests.test_login.Test_TestOne object at 0x0000028155244200>, setup = <selenium.webdriver.edge.webdriver.WebDriver (session=\"83fb7b644da14bdd539c778a907a7042\")>\n\n    @pytest.mark.consy\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_loginTestsOne(self, setup):\n        self.driver = setup\n        self.driver.get(self.bankingURL)\n        self.driver.maximize_window()\n        self.login = LoginPage(self.driver)\n        self.login.clickCustomerLoginButton()\n        self.login.enterCustomerName(self.customer1)\n        self.login.clickLoginButton()\n>       self.login.enterAccountNumber(self.accountNumber1)\nE       AttributeError: 'Test_TestOne' object has no attribute 'accountNumber1'\n\nTests\\test_login.py:23: AttributeError"}, "attachments": [{"name": "log", "source": "7a634a15-fc7f-4bb1-a7cb-16dcae3fbe88-attachment.txt", "type": "text/plain"}], "start": 1729620645358, "stop": 1729620666353, "uuid": "12db5d9b-c1dc-4874-90a0-92f85234c2cc", "historyId": "16354c69e511ecc93a3c1ceee382e6a5", "testCaseId": "16354c69e511ecc93a3c1ceee382e6a5", "fullName": "Tests.test_login.Test_TestOne#test_loginTestsOne", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "consy"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_TestOne"}, {"name": "host", "value": "ZAJ-TUTJACONS"}, {"name": "thread", "value": "2600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}